Sylius\Component\Customer\Model\Customer:
    exclusion_policy: ALL
    xml_root_name: sylius_customer
    properties:
        id:
            expose: true
            type: integer
            groups: [Default, Detailed, DetailedCart]
        email:
            expose: true
            type: string
            groups: [Default, Detailed, DetailedCart]
        firstName:
            expose: true
            type: string
            groups: [Default, Detailed, DetailedCart]
        lastName:
            expose: true
            type: string
            groups: [Default, Detailed, DetailedCart]
        # Updated property code
        emailCanonical:
            expose: true
            type: string
            groups: [Default, Detailed]
        gender:
            expose: true
            type: string
            groups: [Default, Detailed]
        birthday:
            expose: true
            type: DateTime
            groups: [Default, Detailed]
        group:
            expose: true
            groups: [Default, Detailed]
        phoneNumber:
            expose: true
            groups: [Default, Detailed]
        subscribedToNewsletter:
            expose: true
            groups: [Default, Detailed]
        updatedAt:
            expose: true
            groups: [Default, Detailed]
        createdAt:
            expose: true
            groups: [Default, Detailed]
