Sylius\Component\Core\Model\Order:
    exclusion_policy: ALL
    xml_root_name: order
    properties:
        checkoutState:
            expose: true
            type: string
            groups: [Default, Detailed, DetailedCart]
        currencyCode:
            expose: true
            type: string
            groups: [Default, Detailed, DetailedCart]
        localeCode:
            expose: true
            type: string
            groups: [Default, Detailed, DetailedCart]
        shippingAddress:
            expose: true
            groups: [Default, Detailed]
        billingAddress:
            expose: true
            groups: [Default, Detailed]
        shipments:
            expose: true
            groups: [Default, Detailed]
        payments:
            expose: true
            groups: [Default, Detailed]
        customer:
            expose: true
            groups: [Default, Detailed, DetailedCart]
        channel:
            expose: true
            groups: [Default, Detailed, DetailedCart]
        promotionCoupon:
            expose: true
            groups: [Default, Detailed, DetailedCart]
        createdAt:
            expose: true
            type: DateTime
            groups: [Default, Detailed]
        updatedAt:
            expose: true
            type: DateTime
            groups: [Default, Detailed]
